### ISSUE TITLE
`npm run build` doesn't output anything, "This is meant to be run from within npm script." message

### ISSUE THREAD

**Issue by svioletg** [r0x0r/pywebview-react-boilerplate#22]
After trying to run `npm run build` to test it out, I get the following at the end:

```
> pywebview-react-boilerplate@1.0.0 frontend:prod
> parcel build src/index.html --public-url . --no-source-maps -d gui

√  Built in 7.97s.

gui\src.9e253cc5.js                                              132.24 KB    6.14s
gui\logo.2415b4bd.png                                             45.58 KB    2.77s
gui\roboto-condensed-v18-latin_cyrillic-regular.db90b551.woff     27.95 KB    205ms
gui\open-sans-v17-latin_cyrillic-regular.ff111bf4.woff            24.02 KB    443ms
gui\open-sans-v17-latin_cyrillic-italic.026dc2c1.woff             23.28 KB    206ms
gui\src.f2e484e2.css                                               1.89 KB    6.00s
gui\src.55974a2c.css                                                 843 B    5.75s
gui\index.html                                                       304 B    1.60s
This is meant to be run from within npm script. See https://github.com/charlesguse/run-script-os
```

The same message appears if I attempt `npm run start` - the `dist` folder isn't created nor in the binary created anywhere, and `start` doesn't launch anything - but running `py src/index.py` launches the app just fine.

**Comment by mihow** [comment]
Something may have changed with the `run-script-os` tool. My workaround for now is to run each command for my specific operating system: `npm run build:macos`

**Comment by sujalwastaken** [comment]
Hello there!
I think I am a bit late to respond but I resolved the issues on Linux and probably on Windows too. I have made a PR #23

I did a couple of things:
1. Bumped all dependencies, specifically "run-script-os" because of this [issue](https://github.com/charlesguse/run-script-os/issues/42) in version 1.0.7.
2. Removed "--onefile" for linux since it throws error, instead updated spec files in order to create true standalone executable.

I only checked these changes in linux environment, and I have no idea if it will for windows and macos though.

I hope this comment will help others in the future. If my PR is not accepted, you can use my [fork](https://github.com/sujalwastaken/pywebview-react-boilerplate).

**Comment by r0x0r** [comment]
Thanks to @sujalwastaken, this is now fixed
